var items = 
[
	{"name":"Agro Tools", "type": "tools", "id":"0", 
		"img":"../Images/Items/tools1.png", 
		"description":"Sed non purus nec mi rutrum iaculis. Proin ex nunc, varius ut ipsum vel, rhoncus faucibus nisi. ",
		"price":"78$", "location":"Tbilisi", 'delivery':'Yes'},
	{"name":"Agro Tools", "type": "tools", "id":"1", 
		"img":"../Images/Items/tools2.jpg", 
		"description":" mi rutrum iaculis. Proin ex nunc, varius ut ipsum vel, rhoncus faucibus nisi. ",
		"price":"85$", "location":"Kutaisi", 'delivery':'No'},
	{"name":"Agro Tools", "type": "tools", "id":"2", 
		"img":"../Images/Items/tools3.jpg", 
		"description":"Scelerisque in dictum non consectetur a erat nam at lectus. ",
		"price":"94$", "location":"Batumi", 'delivery':'Yes'},

	{"name":"Tractor", "type": "transport", "id":"3", 
		"img":"../Images/Items/tractor1.jpg", 
		"description":"Arcu felis bibendum ut tristique et. Sed adipiscing diam donec adipiscing tristique. ",
		"price":"4700$", "location":"Batumi", 'delivery':'No'},
	{"name":"Tractor", "type": "transport", "id":"4", 
		"img":"../Images/Items/tractor2.jpg", 
		"description":"Semper feugiat nibh sed pulvinar proin. Habitant morbi tristique senectus et.",
		"price":"7100$", "location":"Tbilisi", 'delivery':'No'},
	{"name":"Tractor", "type": "transport", "id":"5", 
		"img":"../Images/Items/tractor3.jpg", 
		"description":"Senectus et netus et malesuada. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. ",
		"price":"10200$", "location":"Kutaisi", 'delivery':'No'},
	{"name":"Tractor", "type": "transport", "id":"6", 
		"img":"../Images/Items/tractor4.png", 
		"description":"Tellus pellentesque eu tincidunt tortor. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur.",
		"price":"15700$", "location":"Tbilisi", 'delivery':'No'},
]